[tool.black]
line-length = 100
target-version = ['py310']

[tool.isort]
py_version = 310
profile = "black"

[tool.pydocstyle]
convention = "google"

[tool.mypy]
python_version = "3.10"
allow_untyped_globals = true
plugins = "mypy_django_plugin.{{ project_name }}"
exclude = "(migrations)"
follow_imports = "silent"


[tool.django-stubs]
django_settings_module = "{{ project_name }}.settings.dev"

[[tool.mypy.overrides]]
module = [
	'celery.*',
	'debug_toolbar.*',
	'setuptools.*',
	'decouple.*',
]
ignore_missing_imports = true

[tool.pytest]
mock_use_standalone_module = true

[tool.pytest.ini_options]
minversion = "6.0"
#addopts = "-n auto"
DJANGO_SETTINGS_MODULE = "{{ project_name }}.settings.test"
python_files = "tests.py test_*.py *_tests.py tests_*.py"
required_plugins = "pytest-mock pytest-django pytest-cov"
